<?php $success = trim((string)($_GET['success'] ?? '')); $error = trim((string)($_GET['error'] ?? '')); ?>
<div class="space-y-5">
    <header class="rounded-xl border border-slate-200 bg-white px-5 py-5">
        <div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
            <div><p class="text-xs font-semibold uppercase tracking-wider text-indigo-600">应用商店</p><h1 class="mt-1 text-2xl font-bold text-slate-900">插件管理</h1><p class="mt-1 text-sm text-slate-500">启停插件、修改设置或安装 ZIP 插件包。</p></div>
            <div class="flex flex-col gap-2 sm:flex-row"><a class="rounded-lg border border-slate-200 px-3 py-2 text-center text-sm font-semibold text-slate-700 hover:bg-slate-50" href="<?= url('/admin/app-store?type=plugin') ?>">浏览插件</a><form class="flex gap-2" action="<?= url('/admin/app-store/plugins/upload') ?>" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input class="min-w-0 max-w-56 rounded-lg border border-slate-200 bg-white px-2 py-1.5 text-xs text-slate-600" type="file" name="plugin_zip" accept=".zip" required><button class="shrink-0 rounded-lg bg-indigo-600 px-3 py-2 text-sm font-semibold text-white hover:bg-indigo-700" type="submit">安装 ZIP</button></form></div>
        </div>
        <div class="mt-4 flex flex-wrap gap-x-5 gap-y-2 border-t border-slate-100 pt-4 text-sm text-slate-500"><span><strong class="text-slate-900"><?= count($plugins) ?></strong> 个已安装</span><span><strong class="text-slate-900"><?= count(array_filter($plugins, static fn(array $plugin): bool => ($plugin['status'] ?? '') === 'enabled')) ?></strong> 个已启用</span><span>Plugin API 1.0</span></div>
    </header>

    <?php if ($success): ?><div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700"><?= h($success) ?></div><?php endif; ?>
    <?php if ($error): ?><div class="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700"><?= h($error) ?></div><?php endif; ?>

    <div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]">
        <div class="space-y-3">
            <?php if ($plugins === []): ?><div class="rounded-xl border border-dashed border-slate-300 bg-white p-12 text-center"><i class="fas fa-plug text-2xl text-slate-300"></i><h2 class="mt-3 font-bold text-slate-800">尚未安装插件</h2><p class="mt-1 text-sm text-slate-500">从应用商店选择插件，或上传 ZIP 插件包。</p></div><?php endif; ?>
            <?php foreach ($plugins as $plugin): $manifest = $plugin['manifest']; $rollbackVersions = array_values(array_filter($plugin['available_versions'] ?? [], static fn($version) => $version !== ($plugin['active_version'] ?? ''))); ?>
                <article class="rounded-xl border border-slate-200 bg-white p-4">
                    <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                        <div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><h2 class="font-bold text-slate-900"><?= h($plugin['name']) ?></h2><span class="rounded-md px-2 py-1 text-xs font-semibold <?= $plugin['status'] === 'enabled' ? 'bg-emerald-50 text-emerald-700' : ($plugin['status'] === 'error' ? 'bg-rose-50 text-rose-700' : 'bg-slate-100 text-slate-600') ?>"><?= h($plugin['status']) ?></span><?php if ($plugin['active_version'] && $plugin['active_version'] !== $plugin['installed_version']): ?><span class="rounded-md bg-amber-50 px-2 py-1 text-xs font-semibold text-amber-700">待升级</span><?php endif; ?></div><p class="mt-1 text-xs text-slate-500"><?= h($plugin['plugin_id']) ?> · v<?= h($plugin['active_version'] ?: $plugin['installed_version']) ?> · <?= h($plugin['vendor']) ?></p><p class="mt-2 text-sm leading-5 text-slate-600"><?= h($plugin['description']) ?></p></div>
                        <div class="flex shrink-0 gap-2"><?php if (($manifest['settings'] ?? []) !== []): ?><a class="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50" href="<?= url('/admin/app-store/plugins/settings?id=' . rawurlencode($plugin['plugin_id'])) ?>">设置</a><?php endif; ?><form action="<?= url('/admin/app-store/plugins/action') ?>" method="post"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="plugin_id" value="<?= h($plugin['plugin_id']) ?>"><input type="hidden" name="action" value="<?= $plugin['status'] === 'enabled' ? 'disable' : 'enable' ?>"><button class="rounded-lg bg-indigo-600 px-3 py-2 text-sm font-semibold text-white hover:bg-indigo-700" type="submit"><?= $plugin['status'] === 'enabled' ? '停用' : '启用' ?></button></form></div>
                    </div>
                    <div class="mt-3 flex flex-wrap gap-x-5 gap-y-1 border-t border-slate-100 pt-3 text-xs text-slate-500"><span>路由 <?= count($manifest['routes'] ?? []) ?></span><span>事件/过滤器 <?= count($manifest['events'] ?? []) + count($manifest['filters'] ?? []) ?></span><span>服务 <?= count($manifest['services'] ?? []) ?></span><span>任务 <?= count($manifest['jobs'] ?? []) ?></span></div>
                    <?php if ($plugin['last_error']): ?><pre class="mt-3 overflow-auto rounded-lg bg-rose-50 p-3 text-xs text-rose-700"><?= h($plugin['last_error']) ?></pre><?php endif; ?>
                    <details class="mt-3 border-t border-slate-100 pt-3 text-sm"><summary class="cursor-pointer font-semibold text-slate-600">更多操作与技术信息</summary><div class="mt-3 space-y-3">
                        <?php if ($rollbackVersions !== []): ?><form class="flex flex-wrap items-center gap-2 rounded-lg bg-amber-50 p-3" action="<?= url('/admin/app-store/plugins/action') ?>" method="post" onsubmit="return confirm('切换插件代码版本？数据库迁移不会反向删除。')"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="plugin_id" value="<?= h($plugin['plugin_id']) ?>"><input type="hidden" name="action" value="rollback"><label class="text-xs font-semibold text-amber-800">版本切换</label><select class="rounded-md border border-amber-200 bg-white px-2 py-1 text-xs" name="target_version"><?php foreach ($rollbackVersions as $version): ?><option value="<?= h($version) ?>">v<?= h($version) ?></option><?php endforeach; ?></select><button class="rounded-md bg-amber-600 px-3 py-1 text-xs font-semibold text-white">切换版本</button></form><?php endif; ?>
                        <details class="rounded-lg bg-slate-50 p-3 text-xs text-slate-600"><summary class="cursor-pointer font-semibold text-slate-700">依赖、权限与扩展清单</summary><div class="mt-3 grid gap-3 sm:grid-cols-2"><div><strong>环境要求</strong><pre class="mt-1 whitespace-pre-wrap"><?= h(json_encode($manifest['requires'] ?? [], JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT)) ?></pre></div><div><strong>插件依赖</strong><pre class="mt-1 whitespace-pre-wrap"><?= h(json_encode($manifest['dependencies'] ?? [], JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT)) ?></pre></div><div><strong>路由</strong><pre class="mt-1 whitespace-pre-wrap"><?= h(json_encode(array_column($manifest['routes'] ?? [], 'path'), JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT)) ?></pre></div><div><strong>服务与权限</strong><pre class="mt-1 whitespace-pre-wrap"><?= h(json_encode(['services' => array_keys($manifest['services'] ?? []), 'permissions' => $manifest['permissions'] ?? []], JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT)) ?></pre></div></div></details>
                        <div class="flex flex-wrap gap-2"><form action="<?= url('/admin/app-store/plugins/action') ?>" method="post" onsubmit="return confirm('移除插件代码？业务数据会保留。')"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="plugin_id" value="<?= h($plugin['plugin_id']) ?>"><input type="hidden" name="action" value="remove"><button class="rounded-lg border border-rose-200 px-3 py-2 text-xs font-semibold text-rose-700" type="submit">移除代码并保留数据</button></form><form action="<?= url('/admin/app-store/plugins/action') ?>" method="post" onsubmit="return confirm('永久删除插件代码、设置、任务和全部插件数据表？此操作不可恢复。')"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="plugin_id" value="<?= h($plugin['plugin_id']) ?>"><input type="hidden" name="action" value="purge"><button class="rounded-lg border border-rose-300 bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700" type="submit">永久清除全部数据</button></form></div>
                    </div></details>
                </article>
            <?php endforeach; ?>
        </div>

        <aside class="space-y-3">
            <details class="rounded-xl border border-slate-200 bg-white" open><summary class="flex cursor-pointer list-none items-center justify-between px-4 py-3 font-bold text-slate-900"><span>环境诊断</span><span class="text-xs font-normal text-slate-400">共享主机</span></summary><div class="border-t border-slate-100 p-4"><dl class="space-y-2 text-sm"><?php foreach ($diagnostics as $key => $value): ?><div class="flex justify-between gap-3"><dt class="text-slate-500"><?= h($key) ?></dt><dd class="font-semibold text-slate-800"><?= h(is_bool($value) ? ($value ? '可用' : '不可用') : $value) ?></dd></div><?php endforeach; ?></dl><label class="mt-4 block text-xs font-semibold text-slate-500">Cron URL<input class="mt-1.5 w-full rounded-lg border border-slate-200 bg-slate-50 px-2 py-2 text-xs" readonly value="<?= h($cronUrl) ?>"></label><form class="mt-3" action="<?= url('/admin/app-store/plugins/action') ?>" method="post"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="action" value="rebuild"><button class="text-xs font-semibold text-indigo-600">重建插件缓存</button></form></div></details>
            <details class="rounded-xl border border-slate-200 bg-white" <?= $jobs !== [] ? 'open' : '' ?>><summary class="flex cursor-pointer list-none items-center justify-between px-4 py-3 font-bold text-slate-900"><span>任务队列</span><span class="text-xs font-normal text-slate-400"><?= count($jobs) ?> 项</span></summary><div class="border-t border-slate-100 p-4"><form class="mb-3" action="<?= url('/admin/app-store/plugins/jobs/run') ?>" method="post"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><button class="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold text-indigo-600">立即执行任务</button></form><div class="space-y-2 text-xs"><?php foreach (array_slice($jobs, 0, 8) as $job): ?><div class="rounded-lg bg-slate-50 p-3"><strong><?= h($job['plugin_id'] . ':' . $job['job_name']) ?></strong><p class="mt-1 text-slate-500"><?= h($job['status']) ?> · <?= (int)$job['progress'] ?>%</p><?php if (in_array($job['status'], ['failed','cancelled','retry'], true)): ?><form class="mt-2 inline" action="<?= url('/admin/app-store/plugins/jobs/action') ?>" method="post"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="job_id" value="<?= (int)$job['id'] ?>"><input type="hidden" name="action" value="retry"><button class="font-semibold text-indigo-600">重试</button></form><?php endif; ?><?php if (in_array($job['status'], ['pending','retry','failed'], true)): ?><form class="ml-3 mt-2 inline" action="<?= url('/admin/app-store/plugins/jobs/action') ?>" method="post"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="job_id" value="<?= (int)$job['id'] ?>"><input type="hidden" name="action" value="cancel"><button class="font-semibold text-rose-600">取消</button></form><?php endif; ?></div><?php endforeach; ?><?php if ($jobs === []): ?><p class="text-slate-500">暂无任务</p><?php endif; ?></div></div></details>
            <details class="rounded-xl border border-slate-200 bg-white"><summary class="flex cursor-pointer list-none items-center justify-between px-4 py-3 font-bold text-slate-900"><span>最近日志</span><span class="text-xs font-normal text-slate-400"><?= count($logs) ?> 条</span></summary><div class="max-h-72 space-y-2 overflow-auto border-t border-slate-100 p-4 text-xs"><?php foreach ($logs as $log): ?><div class="border-b border-slate-100 pb-2"><strong><?= h($log['plugin_id']) ?></strong> <span class="text-slate-400"><?= h($log['level']) ?></span><p class="mt-1 text-slate-600"><?= h($log['message']) ?></p></div><?php endforeach; ?><?php if ($logs === []): ?><p class="text-slate-500">暂无日志</p><?php endif; ?></div></details>
        </aside>
    </div>
</div>
