<?php $success = trim((string)($_GET['success'] ?? '')); $error = trim((string)($_GET['error'] ?? '')); ?>
<div class="space-y-6">
    <div class="flex flex-col gap-4 rounded-3xl bg-gradient-to-r from-indigo-600 to-violet-600 p-6 text-white shadow-lg sm:flex-row sm:items-center sm:justify-between">
        <div><p class="text-sm font-semibold text-indigo-100">ShopAgg Plugin API 1.0</p><h1 class="mt-1 text-2xl font-bold">插件中心</h1><p class="mt-2 text-sm text-indigo-100">安装完整业务模块、后台工具、API、Webhook 与分片任务。</p></div>
        <div class="flex flex-col gap-2 sm:flex-row"><a class="rounded-xl border border-white/30 px-4 py-2 text-center text-sm font-bold text-white" href="<?= url('/admin/app-store?type=plugin') ?>">浏览应用商店</a><form class="flex flex-col gap-2 sm:flex-row" action="<?= url('/admin/plugins/upload') ?>" method="post" enctype="multipart/form-data">
            <input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>">
            <input class="rounded-xl bg-white px-3 py-2 text-sm text-slate-700" type="file" name="plugin_zip" accept=".zip" required>
            <button class="rounded-xl bg-white px-4 py-2 text-sm font-bold text-indigo-600" type="submit">安装 ZIP</button>
        </form></div>
    </div>
    <?php if ($success): ?><div class="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-700"><?= h($success) ?></div><?php endif; ?>
    <?php if ($error): ?><div class="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-rose-700"><?= h($error) ?></div><?php endif; ?>

    <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]">
        <div class="space-y-4">
            <?php if ($plugins === []): ?><div class="rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center text-slate-500">尚未安装插件。可上传 AI 生成的 ZIP 插件包。</div><?php endif; ?>
            <?php foreach ($plugins as $plugin): $manifest = $plugin['manifest']; ?>
                <article class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
                    <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                        <div><div class="flex items-center gap-2"><h2 class="text-lg font-bold text-slate-900"><?= h($plugin['name']) ?></h2><span class="rounded-full px-2.5 py-1 text-xs font-bold <?= $plugin['status'] === 'enabled' ? 'bg-emerald-100 text-emerald-700' : ($plugin['status'] === 'error' ? 'bg-rose-100 text-rose-700' : 'bg-slate-100 text-slate-600') ?>"><?= h($plugin['status']) ?></span><?php if ($plugin['active_version'] && $plugin['active_version'] !== $plugin['installed_version']): ?><span class="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-bold text-amber-700">待升级</span><?php endif; ?></div><p class="mt-1 text-sm text-slate-500"><?= h($plugin['plugin_id']) ?> · 已安装 v<?= h($plugin['installed_version']) ?><?php if ($plugin['active_version']): ?> · 当前 v<?= h($plugin['active_version']) ?><?php endif; ?> · <?= h($plugin['vendor']) ?></p><p class="mt-3 text-sm text-slate-600"><?= h($plugin['description']) ?></p></div>
                        <div class="flex flex-wrap gap-2">
                            <?php if (($manifest['settings'] ?? []) !== []): ?><a class="rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold" href="<?= url('/admin/plugins/settings?id=' . rawurlencode($plugin['plugin_id'])) ?>">设置</a><?php endif; ?>
                            <form action="<?= url('/admin/plugins/action') ?>" method="post"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="plugin_id" value="<?= h($plugin['plugin_id']) ?>"><input type="hidden" name="action" value="<?= $plugin['status'] === 'enabled' ? 'disable' : 'enable' ?>"><button class="rounded-xl bg-indigo-600 px-3 py-2 text-sm font-semibold text-white" type="submit"><?= $plugin['status'] === 'enabled' ? '停用' : '启用' ?></button></form>
                            <form action="<?= url('/admin/plugins/action') ?>" method="post" onsubmit="return confirm('移除插件代码？业务数据会保留。')"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="plugin_id" value="<?= h($plugin['plugin_id']) ?>"><input type="hidden" name="action" value="remove"><button class="rounded-xl border border-rose-200 px-3 py-2 text-sm font-semibold text-rose-600" type="submit">移除</button></form>
                            <form action="<?= url('/admin/plugins/action') ?>" method="post" onsubmit="return confirm('永久删除插件代码、设置、任务和全部插件数据表？此操作不可恢复。')"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="plugin_id" value="<?= h($plugin['plugin_id']) ?>"><input type="hidden" name="action" value="purge"><button class="rounded-xl border border-rose-300 bg-rose-50 px-3 py-2 text-sm font-semibold text-rose-700" type="submit">永久清除</button></form>
                        </div>
                    </div>
                    <?php $rollbackVersions = array_values(array_filter($plugin['available_versions'] ?? [], static fn($version) => $version !== ($plugin['active_version'] ?? ''))); if ($rollbackVersions !== []): ?><form class="mt-4 flex flex-wrap items-center gap-2 rounded-2xl bg-amber-50 p-3" action="<?= url('/admin/plugins/action') ?>" method="post" onsubmit="return confirm('切换插件代码版本？数据库迁移不会反向删除。')"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="plugin_id" value="<?= h($plugin['plugin_id']) ?>"><input type="hidden" name="action" value="rollback"><label class="text-xs font-semibold text-amber-800">版本切换</label><select class="rounded-lg border border-amber-200 bg-white px-2 py-1 text-xs" name="target_version"><?php foreach ($rollbackVersions as $version): ?><option value="<?= h($version) ?>">v<?= h($version) ?></option><?php endforeach; ?></select><button class="rounded-lg bg-amber-600 px-3 py-1 text-xs font-bold text-white">回滚/切换</button></form><?php endif; ?>
                    <div class="mt-4 grid gap-3 text-xs text-slate-500 sm:grid-cols-4"><div>路由 <?= count($manifest['routes'] ?? []) ?></div><div>事件/过滤器 <?= count($manifest['events'] ?? []) + count($manifest['filters'] ?? []) ?></div><div>服务 <?= count($manifest['services'] ?? []) ?></div><div>任务 <?= count($manifest['jobs'] ?? []) ?></div></div>
                    <details class="mt-4 rounded-2xl bg-slate-50 p-3 text-xs text-slate-600"><summary class="cursor-pointer font-semibold text-slate-800">依赖、权限与扩展清单</summary><div class="mt-3 grid gap-3 sm:grid-cols-2"><div><strong>环境要求</strong><pre class="mt-1 whitespace-pre-wrap"><?= h(json_encode($manifest['requires'] ?? [], JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT)) ?></pre></div><div><strong>插件依赖</strong><pre class="mt-1 whitespace-pre-wrap"><?= h(json_encode($manifest['dependencies'] ?? [], JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT)) ?></pre></div><div><strong>路由</strong><pre class="mt-1 whitespace-pre-wrap"><?= h(json_encode(array_column($manifest['routes'] ?? [], 'path'), JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT)) ?></pre></div><div><strong>服务与权限</strong><pre class="mt-1 whitespace-pre-wrap"><?= h(json_encode(['services' => array_keys($manifest['services'] ?? []), 'permissions' => $manifest['permissions'] ?? []], JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT)) ?></pre></div></div></details>
                    <?php if ($plugin['last_error']): ?><pre class="mt-4 overflow-auto rounded-2xl bg-rose-50 p-3 text-xs text-rose-700"><?= h($plugin['last_error']) ?></pre><?php endif; ?>
                </article>
            <?php endforeach; ?>
        </div>
        <aside class="space-y-4">
            <div class="rounded-3xl border border-slate-200 bg-white p-5"><div class="flex items-center justify-between"><h2 class="font-bold text-slate-900">环境诊断</h2><form action="<?= url('/admin/plugins/action') ?>" method="post"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="action" value="rebuild"><button class="text-xs font-semibold text-indigo-600">重建缓存</button></form></div><dl class="mt-4 space-y-2 text-sm"><?php foreach ($diagnostics as $key => $value): ?><div class="flex justify-between gap-3"><dt class="text-slate-500"><?= h($key) ?></dt><dd class="font-semibold text-slate-800"><?= h(is_bool($value) ? ($value ? '可用' : '不可用') : $value) ?></dd></div><?php endforeach; ?></dl><label class="mt-4 block text-xs font-semibold text-slate-500">共享主机 Cron URL<input class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-xs" readonly value="<?= h($cronUrl) ?>"></label></div>
            <div class="rounded-3xl border border-slate-200 bg-white p-5"><div class="flex items-center justify-between"><h2 class="font-bold text-slate-900">任务队列</h2><form action="<?= url('/admin/plugins/jobs/run') ?>" method="post"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><button class="text-sm font-semibold text-indigo-600">执行</button></form></div><div class="mt-4 space-y-2 text-xs"><?php foreach (array_slice($jobs, 0, 8) as $job): ?><div class="rounded-xl bg-slate-50 p-3"><strong><?= h($job['plugin_id'] . ':' . $job['job_name']) ?></strong><p class="mt-1 text-slate-500"><?= h($job['status']) ?> · <?= (int)$job['progress'] ?>%</p><?php if (in_array($job['status'], ['failed','cancelled','retry'], true)): ?><form class="mt-2 inline" action="<?= url('/admin/plugins/jobs/action') ?>" method="post"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="job_id" value="<?= (int)$job['id'] ?>"><input type="hidden" name="action" value="retry"><button class="font-semibold text-indigo-600">重试</button></form><?php endif; ?><?php if (in_array($job['status'], ['pending','retry','failed'], true)): ?><form class="ml-3 mt-2 inline" action="<?= url('/admin/plugins/jobs/action') ?>" method="post"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="job_id" value="<?= (int)$job['id'] ?>"><input type="hidden" name="action" value="cancel"><button class="font-semibold text-rose-600">取消</button></form><?php endif; ?></div><?php endforeach; ?><?php if ($jobs === []): ?><p class="text-slate-500">暂无任务</p><?php endif; ?></div></div>
            <div class="rounded-3xl border border-slate-200 bg-white p-5"><h2 class="font-bold text-slate-900">最近日志</h2><div class="mt-4 max-h-64 space-y-2 overflow-auto text-xs"><?php foreach ($logs as $log): ?><div class="border-b border-slate-100 pb-2"><strong><?= h($log['plugin_id']) ?></strong> <span class="text-slate-400"><?= h($log['level']) ?></span><p class="mt-1 text-slate-600"><?= h($log['message']) ?></p></div><?php endforeach; ?></div></div>
        </aside>
    </div>
</div>
