<?php
$query = (string)($filters['query'] ?? '');
$type = (string)($filters['type'] ?? 'all');
$status = (string)($filters['status'] ?? 'all');
$price = (string)($filters['price'] ?? 'all');
?>
<div class="space-y-6">
    <section class="overflow-hidden rounded-3xl bg-gradient-to-br from-indigo-700 via-violet-700 to-fuchsia-700 p-7 text-white shadow-xl">
        <div class="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between">
            <div><p class="text-sm font-semibold text-indigo-100">ShopAGG App Store</p><h1 class="mt-1 text-3xl font-bold">应用商店</h1><p class="mt-2 max-w-2xl text-sm leading-6 text-indigo-100">在一个地方发现网站插件和主题，扩展业务功能或快速更换网站外观。</p></div>
            <div class="grid grid-cols-3 gap-3 text-center text-sm"><div class="rounded-2xl bg-white/10 px-4 py-3"><strong class="block text-xl"><?= (int)$counts['plugin'] ?></strong>插件</div><div class="rounded-2xl bg-white/10 px-4 py-3"><strong class="block text-xl"><?= (int)$counts['theme'] ?></strong>主题</div><div class="rounded-2xl bg-white/10 px-4 py-3"><strong class="block text-xl"><?= (int)$counts['installed'] ?></strong>已安装</div></div>
        </div>
    </section>

    <?php if (!$hasToken): ?><div class="flex flex-col gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800 sm:flex-row sm:items-center sm:justify-between"><div><strong>尚未绑定 ShopAGG 账户</strong><p class="mt-1">可以浏览应用；下载安装付费或授权资源前需要配置 App Store Token。</p></div><a class="shrink-0 rounded-xl bg-amber-600 px-4 py-2 font-semibold text-white" href="<?= url('/admin/appearance/themes#app-store-account') ?>">配置账户</a></div><?php endif; ?>
    <?php foreach ($errors as $error): ?><div class="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><?= h($error) ?></div><?php endforeach; ?>

    <form class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm" method="get" action="<?= url('/admin/app-store') ?>">
        <div class="grid gap-4 lg:grid-cols-[minmax(240px,1fr)_180px_180px_160px_auto] lg:items-end">
            <label class="block"><span class="mb-2 block text-xs font-bold uppercase tracking-wider text-slate-400">搜索应用</span><span class="relative block"><i class="fas fa-search absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"></i><input class="w-full rounded-xl border border-slate-200 py-3 pl-11 pr-4 outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100" type="search" name="q" value="<?= h($query) ?>" placeholder="名称、开发者、功能或标签"></span></label>
            <label><span class="mb-2 block text-xs font-bold uppercase tracking-wider text-slate-400">应用类型</span><select class="w-full rounded-xl border border-slate-200 px-3 py-3" name="type"><option value="all">全部类型</option><option value="plugin" <?= $type === 'plugin' ? 'selected' : '' ?>>插件</option><option value="theme" <?= $type === 'theme' ? 'selected' : '' ?>>网站主题</option></select></label>
            <label><span class="mb-2 block text-xs font-bold uppercase tracking-wider text-slate-400">安装状态</span><select class="w-full rounded-xl border border-slate-200 px-3 py-3" name="status"><option value="all">全部状态</option><option value="available" <?= $status === 'available' ? 'selected' : '' ?>>未安装</option><option value="installed" <?= $status === 'installed' ? 'selected' : '' ?>>已安装</option><option value="update" <?= $status === 'update' ? 'selected' : '' ?>>可更新</option></select></label>
            <label><span class="mb-2 block text-xs font-bold uppercase tracking-wider text-slate-400">价格</span><select class="w-full rounded-xl border border-slate-200 px-3 py-3" name="price"><option value="all">全部价格</option><option value="free" <?= $price === 'free' ? 'selected' : '' ?>>免费</option><option value="paid" <?= $price === 'paid' ? 'selected' : '' ?>>付费</option></select></label>
            <div class="flex gap-2"><button class="rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white" type="submit">筛选</button><a class="rounded-xl border border-slate-200 px-4 py-3 font-semibold text-slate-600" href="<?= url('/admin/app-store') ?>">重置</a></div>
        </div>
    </form>

    <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-xl font-bold text-slate-900">应用与主题</h2><p class="mt-1 text-sm text-slate-500">找到 <?= count($items) ?> 个符合条件的结果</p></div><div class="flex gap-2"><a class="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700" href="<?= url('/admin/plugins') ?>"><i class="fas fa-plug mr-2 text-violet-500"></i>管理插件</a><a class="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700" href="<?= url('/admin/appearance/themes') ?>"><i class="fas fa-swatchbook mr-2 text-sky-500"></i>管理主题</a></div></div>

    <?php if ($items === []): ?><div class="rounded-3xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><div class="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-slate-100 text-2xl text-slate-400"><i class="fas fa-search"></i></div><h2 class="mt-5 text-lg font-bold text-slate-800">没有找到匹配应用</h2><p class="mt-2 text-sm text-slate-500">尝试更换关键词或清除筛选条件。</p></div><?php else: ?>
        <div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
            <?php foreach ($items as $item): ?>
                <article data-app-type="<?= h($item['type']) ?>" data-app-installed="<?= $item['installed'] ? '1' : '0' ?>" class="flex min-h-[320px] flex-col overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg">
                    <div class="flex gap-4 border-b border-slate-100 p-5"><div class="flex h-16 w-16 shrink-0 items-center justify-center overflow-hidden rounded-2xl <?= $item['type'] === 'plugin' ? 'bg-violet-100 text-violet-600' : 'bg-sky-100 text-sky-600' ?> text-2xl"><?php if ($item['image']): ?><img class="h-full w-full object-cover" src="<?= h($item['image']) ?>" alt=""><?php else: ?><i class="fas fa-<?= $item['type'] === 'plugin' ? 'plug' : 'swatchbook' ?>"></i><?php endif; ?></div><div class="min-w-0 flex-1"><div class="flex items-start justify-between gap-2"><div><span class="text-xs font-bold uppercase tracking-wider <?= $item['type'] === 'plugin' ? 'text-violet-600' : 'text-sky-600' ?>"><?= $item['type'] === 'plugin' ? '插件' : '网站主题' ?></span><h3 class="mt-1 truncate text-lg font-bold text-slate-900"><?= h($item['name']) ?></h3></div><span class="shrink-0 rounded-full <?= $item['is_free'] ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700' ?> px-2.5 py-1 text-xs font-bold"><?= h($item['price_text']) ?></span></div><p class="mt-1 truncate text-xs text-slate-500"><?= h($item['vendor']) ?><?php if ($item['version']): ?> · v<?= h($item['version']) ?><?php endif; ?></p></div></div>
                    <div class="flex-1 p-5"><p class="line-clamp-3 min-h-[66px] text-sm leading-6 text-slate-600"><?= h($item['description'] ?: '暂无应用介绍') ?></p><?php if ($item['tags']): ?><div class="mt-4 flex flex-wrap gap-2"><?php foreach (array_slice($item['tags'], 0, 4) as $tag): ?><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-600"><?= h($tag) ?></span><?php endforeach; ?></div><?php endif; ?><div class="mt-4 flex gap-2"><?php if ($item['installed']): ?><span class="rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-700"><?= $item['needs_update'] ? '有可用更新' : '已安装' ?><?php if ($item['installed_version']): ?> · v<?= h($item['installed_version']) ?><?php endif; ?></span><?php endif; ?></div></div>
                    <div class="border-t border-slate-100 bg-slate-50 p-4"><?php if ($item['installed']): ?><a class="flex w-full items-center justify-center rounded-xl bg-slate-800 px-4 py-2.5 text-sm font-bold text-white" href="<?= url($item['manage_url']) ?>"><?= $item['needs_update'] ? '查看更新' : '管理' ?></a><?php elseif ($item['type'] === 'theme'): ?><a class="flex w-full items-center justify-center rounded-xl bg-sky-600 px-4 py-2.5 text-sm font-bold text-white" href="<?= url($item['detail_url']) ?>">查看并安装</a><?php else: ?><form action="<?= url('/admin/plugins/market/install') ?>" method="post"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="resource_id" value="<?= (int)$item['id'] ?>"><button class="w-full rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-bold text-white" type="submit">下载安装</button></form><?php endif; ?></div>
                </article>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>
